### ISSUE TITLE
ng commands gives an error

### ISSUE THREAD

**Issue by kkimdev** [m19g/online-test#7]
```
$ ng serve

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/home/kkim/projects/online-test/node_modules/@angular/cli/tasks/serve.js:22:63)
    at check_port_1.checkPort.then.port (/home/kkim/projects/online-test/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by kkimdev** [comment]
Fixed by #8
